import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { randomUUID } from 'node:crypto'
import { chromium } from 'playwright'
import { db, createUser, workout, cleanup, sessionCookie } from './db-helper'
import { getSession, mutateSession } from '../src/server/store'
import { counts } from '../src/lib/domain'
import { measurements } from './fixture'
import { startApp, origin } from './server-helper'

process.env.PLAYWRIGHT_BROWSERS_PATH ??= `${process.cwd()}/.cache/browsers`
test('mobile recording, offline reload/reconnect, conflicts, finishing and account isolation', { timeout: 120000 }, async t => {
  const app = await startApp(), u = await createUser(), second = await createUser()
  const browser = await chromium.launch(), context = await browser.newContext({ viewport: { width: 390, height: 844 } }), page = await context.newPage()
  t.after(async () => { await browser.close(); await app.stop() })
  page.setDefaultTimeout(15000)
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  try {
    const f = await workout(u.id), cookie = await sessionCookie(u.id)
    await context.addCookies([{ ...cookie, value: encodeURIComponent(cookie.value), url: origin, httpOnly: true, sameSite: 'Lax' }])
    await page.goto(`${origin}/workouts/${f.saved.id}`)
    await page.getByRole('button', { name: 'Start workout' }).click()
    await page.waitForURL('**/sessions/*')
    await page.getByRole('heading', { name: 'Workout A', exact: true }).waitFor()
    const sessionId = page.url().split('/').at(-1)!
    let s = await getSession(u.id, sessionId)
    assert.equal(counts(s).completed, 0)
    const bench = s.exercises[2], set = bench.sets[0], range = s.exercises[3].sets[0]
    assert.equal(await page.locator(`#set-${range.id}`).getByRole('spinbutton', { name: /Actual reps/ }).inputValue(), '')
    const row = page.locator(`#set-${set.id}`)
    await row.getByRole('spinbutton', { name: /Actual reps/ }).fill('8')
    await row.getByRole('spinbutton', { name: /Actual load/ }).fill('55')
    await row.getByRole('button', { name: 'Confirm completed set' }).click()
    await row.getByText('✓ Completed', { exact: true }).waitFor()
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    s = await getSession(u.id, sessionId)
    assert.equal(s.exercises[2].sets[0].actualLoadValue, '55')
    assert.equal(s.workout.groups[2].exercises[0].sets[0].loadValue, '60')
    const benchCard = page.locator('.exercise-card').filter({ has: page.getByRole('heading', { name: 'Bench press', exact: true }) })
    await benchCard.getByRole('button', { name: 'Substitute', exact: true }).click()
    await page.getByRole('combobox', { name: 'Exercise identity' }).selectOption(f.catalog[8].id)
    await page.getByRole('button', { name: 'Use this exercise' }).click()
    await page.getByRole('heading', { name: /Lat pulldown/ }).waitFor()
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    const extraCard = page.locator('.exercise-card').filter({ has: page.getByRole('heading', { name: /Lat pulldown/ }) })
    await extraCard.getByRole('button', { name: '＋ Set', exact: true }).click()
    await extraCard.getByText('Unrecorded · Extra', { exact: true }).waitFor()
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    const jumps = page.locator('.exercise-card').filter({ has: page.getByRole('heading', { name: 'Jumps', exact: true }) })
    await jumps.getByRole('button', { name: 'Skip pending exercise work' }).click()
    await jumps.getByText('Skipped', { exact: true }).waitFor()
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    const left = s.exercises[4].sets.find(x => x.setNumber === 1 && x.side === 'LEFT')!, right = s.exercises[4].sets.find(x => x.setNumber === 1 && x.side === 'RIGHT')!
    await page.locator(`#set-${left.id}`).getByRole('spinbutton', { name: /Actual reps/ }).fill('8')
    await page.locator(`#set-${left.id}`).getByRole('button', { name: 'Confirm completed set' }).click()
    await page.locator(`#set-${left.id}`).getByText('✓ Completed', { exact: true }).waitFor()
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    assert.equal((await getSession(u.id, sessionId)).exercises[4].sets.find(x => x.id === right.id)!.status, 'PENDING')
    await page.locator(`#set-${right.id}`).getByRole('spinbutton', { name: /Actual reps/ }).fill('7')
    await page.locator(`#set-${right.id}`).getByRole('button', { name: 'Confirm completed set' }).click()
    await page.locator(`#set-${right.id}`).getByText('✓ Completed', { exact: true }).waitFor()
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    console.log('Browser: sets, substitution, extra work and side mismatch verified; checking offline shell')
    await page.waitForFunction(async () => { const registration = await navigator.serviceWorker.getRegistration(); return registration?.active?.state === 'activated' && !!navigator.serviceWorker.controller }, undefined, { timeout: 15000 })
    const secondLeft = s.exercises[4].sets.find(x => x.setNumber === 2 && x.side === 'LEFT')!
    await context.setOffline(true)
    await page.locator(`#set-${secondLeft.id}`).getByRole('spinbutton', { name: /Actual reps/ }).fill('5')
    await page.locator(`#set-${secondLeft.id}`).getByRole('spinbutton', { name: /Actual load/ }).fill('18.5')
    await page.locator(`#set-${secondLeft.id}`).getByRole('button', { name: 'Confirm completed set' }).click()
    await page.getByRole('status').filter({ hasText: 'Offline · 1 changes retained' }).waitFor()
    await page.reload({ waitUntil: 'domcontentloaded' })
    await page.getByRole('heading', { name: 'Workout A', exact: true }).waitFor()
    assert.equal(await page.locator(`#set-${secondLeft.id}`).getByRole('spinbutton', { name: /Actual reps/ }).inputValue(), '5')
    assert.equal((await getSession(u.id, sessionId)).exercises[4].sets.find(x => x.id === secondLeft.id)!.status, 'PENDING')
    await context.setOffline(false)
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    s = await getSession(u.id, sessionId); assert.equal(s.exercises[4].sets.find(x => x.id === secondLeft.id)!.actualReps, 5)
    // Real conflict: retain offline changes while another device advances the revision.
    await context.setOffline(true)
    await page.locator(`#set-${range.id}`).getByRole('spinbutton', { name: /Actual reps/ }).fill('9')
    await page.locator(`#set-${range.id}`).getByRole('button', { name: 'Confirm completed set' }).click()
    await page.getByRole('status').filter({ hasText: 'Offline · 1 changes retained' }).waitFor()
    await mutateSession(u.id, sessionId, { operationId: randomUUID(), expectedRevision: s.revision, operation: { kind: 'notes', notes: 'Another device' } })
    await context.setOffline(false)
    await page.getByRole('heading', { name: 'Your changes need attention' }).waitFor()
    await page.getByRole('button', { name: 'Reapply compatible local changes' }).click()
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    assert.equal((await getSession(u.id, sessionId)).exercises[3].sets[0].actualReps, 9)
    // Account change cannot upload or disclose this account's retained queue.
    await context.setOffline(true)
    const last = s.exercises[1].sets[0]
    await page.locator(`#set-${last.id}`).getByRole('spinbutton', { name: /Actual reps/ }).fill('4')
    await page.locator(`#set-${last.id}`).getByRole('button', { name: 'Confirm completed set' }).click()
    await page.getByRole('status').filter({ hasText: 'Offline · 1 changes retained' }).waitFor()
    const otherCookie = await sessionCookie(second.id)
    await context.addCookies([{ ...otherCookie, value: encodeURIComponent(otherCookie.value), url: origin, httpOnly: true, sameSite: 'Lax' }])
    await context.setOffline(false)
    await page.getByText('Record not found', { exact: true }).waitFor()
    assert.equal((await getSession(u.id, sessionId)).exercises[1].sets[0].status, 'PENDING')
    await page.goto(`${origin}/sessions/${sessionId}`)
    await page.getByText('Record not found', { exact: true }).waitFor()
    assert.equal(await page.getByRole('heading', { name: 'Workout A', exact: true }).count(), 0)
    // Return to original account and finish offline after the queued set.
    await context.addCookies([{ ...cookie, value: encodeURIComponent(cookie.value), url: origin, httpOnly: true, sameSite: 'Lax' }])
    await page.goto(`${origin}/sessions/${sessionId}`)
    await page.getByRole('status').filter({ hasText: 'Saved on server' }).waitFor()
    await mkdir('test-results', { recursive: true })
    await page.screenshot({ path: 'test-results/mobile-recording.png', fullPage: true })
    await context.setOffline(true)
    await page.getByRole('button', { name: 'Review & finish workout' }).click()
    await page.getByRole('button', { name: 'Finish workout', exact: true }).click()
    await page.getByText('FINISH PENDING SYNCHRONIZATION', { exact: true }).waitFor()
    assert.equal((await getSession(u.id, sessionId)).status, 'ACTIVE')
    await page.reload({ waitUntil: 'domcontentloaded' })
    await page.getByText('FINISH PENDING SYNCHRONIZATION', { exact: true }).waitFor()
    await context.setOffline(false)
    await page.getByText('SESSION FINISHED', { exact: true }).waitFor()
    s = await getSession(u.id, sessionId); assert.equal(s.status, 'FINISHED'); assert.ok(counts(s).unrecorded > 0); assert.equal(counts(s).skipped, 1)
    assert.equal(await page.getByRole('button', { name: 'Confirm completed set' }).count(), 0)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    assert.deepEqual(errors, [])
  } catch (e) { await mkdir('test-results', { recursive: true }); await page.screenshot({ path: 'test-results/browser-failure.png', fullPage: true }).catch(() => {}); await writeFile('test-results/browser-failure.txt', await page.locator('body').innerText().catch(() => 'Page closed')); throw e } finally { await browser.close(); await cleanup([u.id, second.id]); await app.stop() }
})
