/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known.$'
import { Route as ApiDataRouteImport } from './routes/api.data'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/workouts/$id',
  path: '/workouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/data': typeof ApiDataRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/data': typeof ApiDataRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/data': typeof ApiDataRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/workouts/$id': typeof WorkoutsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/mcp'
    | '/offline'
    | '/privacy'
    | '/settings'
    | '/.well-known/$'
    | '/api/data'
    | '/oauth/consent'
    | '/sessions/$id'
    | '/workouts/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/mcp'
    | '/offline'
    | '/privacy'
    | '/settings'
    | '/.well-known/$'
    | '/api/data'
    | '/oauth/consent'
    | '/sessions/$id'
    | '/workouts/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/login'
    | '/mcp'
    | '/offline'
    | '/privacy'
    | '/settings'
    | '/.well-known/$'
    | '/api/data'
    | '/oauth/consent'
    | '/sessions/$id'
    | '/workouts/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiDataRoute: typeof ApiDataRoute
  OauthConsentRoute: typeof OauthConsentRoute
  SessionsIdRoute: typeof SessionsIdRoute
  WorkoutsIdRoute: typeof WorkoutsIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/workouts/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiDataRoute: ApiDataRoute,
  OauthConsentRoute: OauthConsentRoute,
  SessionsIdRoute: SessionsIdRoute,
  WorkoutsIdRoute: WorkoutsIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
